Repository firebase/firebase-admin-node, pull requests merged in 2020-06, with the labels that each got.

#909 fix(auth): Add interfaces for UserProviderRequest and Metadata used in UserImportRecord
  src/auth.d.ts
  src/auth/user-import-builder.ts
  test/integration/auth.spec.ts
Labels: api: auth, release-note

#917 fix(auth): Fixing flaky deleteUsers() integration tests
  src/index.d.ts
  test/integration/auth.spec.ts
Labels: release-note

#916 fix(auth): Migrated IAM sign endpoint to iamcredentials.googleapis.com
  src/auth/token-generator.ts
  test/unit/auth/token-generator.spec.ts
Labels: release:stage

#920 feat(rc): Add Remote Config Version Management API
  src/index.d.ts
  src/remote-config/remote-config-api-client.ts
  src/remote-config/remote-config.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/remote-config/remote-config.spec.ts
Labels: release-note

#914 Add integration tests for RC manage version operations
  src/remote-config/remote-config-api-client.ts
  src/remote-config/remote-config.ts
  test/integration/remote-config.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/remote-config/remote-config.spec.ts
Labels: release:stage

#925 [chore] Release 8.13.0
  package.json
Labels: release:publish, release:tweet
