Repository firebase/firebase-admin-node, pull requests merged in 2020-04, with the labels that each got.

#852 fix(auth): Defines missing `DecodedIdToken` types.
  src/auth.d.ts
  src/auth/auth.ts
Labels: release-note

#859 fix(rtdb): Upgraded @firebase/database dependency to latest available
  package-lock.json
  package.json
  src/database.d.ts
Labels: release-note

#850 feat(machine-learning): Adding Firebase ML management APIs
  CONTRIBUTING.md
  docgen/content-sources/node/toc.yaml
  src/firebase-app.ts
  src/firebase-namespace.ts
  src/index.d.ts
  src/machine-learning/machine-learning-api-client.ts
  src/machine-learning/machine-learning-utils.ts
  src/machine-learning/machine-learning.ts
  test/integration/machine-learning.spec.ts
  test/resources/invalid_model.tflite
  test/resources/model1.tflite
  test/unit/firebase-app.spec.ts
  test/unit/firebase-namespace.spec.ts
  test/unit/index.spec.ts
  test/unit/machine-learning/machine-learning-api-client.spec.ts
  test/unit/machine-learning/machine-learning.spec.ts
  test/unit/utils/api-request.spec.ts
Labels: release:stage

#845 feat: Remote Config Management API
  docgen/content-sources/node/toc.yaml
  src/firebase-app.ts
  src/firebase-namespace.ts
  src/index.d.ts
  src/remote-config/remote-config-api-client.ts
  src/remote-config/remote-config-utils.ts
  src/remote-config/remote-config.ts
  test/integration/remote-config.spec.ts
  test/unit/firebase-app.spec.ts
  test/unit/firebase-namespace.spec.ts
  test/unit/firebase.spec.ts
  test/unit/index.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/remote-config/remote-config.spec.ts
Labels: release-note, release:stage

#861 [chore] Release 8.11.0
  package.json
Labels: release:publish, release:tweet

#866 fix(auth): Refines `UserRecord.customClaims` type.
  package-lock.json
  src/auth.d.ts
  src/auth/user-import-builder.ts
  src/auth/user-record.ts
Labels: release-note
