Repository firebase/firebase-admin-node, pull requests merged in 2020-08, with the labels that each got.

#975 chore(rc): Move manual typings remote-config typings to separate folder
  src/index.d.ts
  src/remote-config.d.ts
Labels: release:stage

#930 feat(auth): Adds ability to enable MFA on a Google Cloud Identity Platform tenant
  docgen/content-sources/node/toc.yaml
  src/auth.d.ts
  src/auth/auth-api-request.ts
  src/auth/auth-config.ts
  src/auth/tenant.ts
  src/utils/error.ts
  src/utils/index.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth-config.spec.ts
  test/unit/auth/tenant.spec.ts
  test/unit/utils/index.spec.ts
Labels: release-note

#991 [chore] Release 9.1.0
  package.json
Labels: release:publish, release:tweet

#996 fix(rc): Add missing class in RemoteConfig Namespace
  src/index.d.ts
Labels: release-note

#1003 [chore] Release 9.1.1
  package.json
Labels: release:publish, release:tweet
