Repository firebase/firebase-admin-node, pull requests merged in 2020-07, with the labels that each got.

#934 change: Dropped Node 8 support and upgraded Firestore/Storage dependencies
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: release-note

#946 [chore] Release 9.0.0
  package.json
Labels: release:publish, release:tweet

#958 fix(auth): Add null to customUserClaims inside BaseAuth.setCustomUserClaims
  src/auth/auth.ts
Labels: api: auth

#961 fix: Use object instead of Object in typings
  src/auth.d.ts
  src/database.d.ts
  src/index.d.ts
Labels: api: auth, type: cleanup

#970 fix(auth): Make displayName optional for AuthProviderConfig typings
  src/auth.d.ts
Labels: release-note
