Repository firebase/firebase-admin-node, pull requests merged in 2020-11, with the labels that each got.

#1079 fix: Adding es2018 libraries to the build
  test/integration/typescript/tsconfig.json
  tsconfig.json
Labels: release:stage

#1080 feat(firestore): Exposed more types from the admin.firestore namespace
  package-lock.json
  package.json
  src/firestore/index.ts
  test/integration/firestore.spec.ts
Labels: release-note, release:stage

#1085 fix(auth): Use 'owner' token when communicating with Auth emulator
  src/auth/auth-api-request.ts
  src/auth/auth.ts
  src/utils/api-request.ts
  test/unit/auth/auth-api-request.spec.ts
Labels: release-note

#1087 [chore] Release 9.4.0
  package.json
Labels: release:publish, release:tweet

#1089 fix(rc): Fix Version update time parsing failure
  src/remote-config/remote-config.ts
  test/unit/remote-config/remote-config.spec.ts
Labels: release:stage

#1091 [chore] Release 9.4.1
  package.json
Labels: release:publish, release:tweet
