Repository firebase/firebase-admin-node, pull requests merged in 2021-09, with the labels that each got.

#1424 feat(rc): Add Remote Config Parameter Value Type Support
  etc/firebase-admin.api.md
  src/remote-config/index.ts
  test/integration/remote-config.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/remote-config/remote-config.spec.ts
Labels: release-note, release:stage

#1437 fix(rtdb): Changed admin.database to use database-compat package
  gulpfile.js
  package-lock.json
  package.json
  src/database/database-internal.ts
  src/database/index.ts
  src/firebase-namespace.ts
  test/integration/app.spec.ts
  test/integration/auth.spec.ts
  test/unit/app-check/token-generator.spec.ts
  test/unit/firebase-namespace.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release-note, release:stage

#1442 [chore] Release 9.12.0
  package.json
Labels: release:tweet, release:publish

#1443 chore: Merging main branch into modular-sdk
  .github/workflows/nightly.yml
  etc/firebase-admin.api.md
  etc/firebase-admin.installations.api.md
  etc/firebase-admin.remote-config.api.md
  gulpfile.js
  package-lock.json
  package.json
  src/app-check/token-generator.ts
  src/app-check/token-verifier.ts
  src/app/firebase-namespace.ts
  src/auth/auth-config.ts
  src/auth/base-auth.ts
  src/auth/tenant-manager.ts
  src/auth/token-generator.ts
  src/auth/token-verifier.ts
  src/database/database.ts
  src/database/index.ts
  src/installations/installations-namespace.ts
  src/installations/installations.ts
  src/instance-id/index.ts
  src/remote-config/index.ts
  src/remote-config/remote-config-api.ts
  src/remote-config/remote-config-namespace.ts
  src/utils/crypto-signer.ts
  src/utils/error.ts
  src/utils/jwt.ts
  test/integration/app.spec.ts
  test/integration/auth.spec.ts
  test/integration/remote-config.spec.ts
  test/unit/app-check/token-generator.spec.ts
  test/unit/app/firebase-namespace.spec.ts
  test/unit/auth/auth.spec.ts
  test/unit/auth/token-verifier.spec.ts
  test/unit/index.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/remote-config/remote-config.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release:stage
