Repository firebase/firebase-admin-node, pull requests merged in 2021-03, with the labels that each got.

#1176 chore: Updated package.json file for entry points
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
  test/integration/typescript/src/example-modular.test.ts
  test/integration/typescript/src/example.test.ts
Labels: release:stage

#1190 feat(rtdb): Support emulator mode for rules management operations
  src/database/database-internal.ts
  test/unit/database/database.spec.ts
Labels: release-note

#1203 fix(rtdb): Fixing the RTDB token listener callback
  src/database/database-internal.ts
  test/unit/database/database.spec.ts
Labels: release:stage

#1209 [chore] Release 9.6.0
  package.json
Labels: release:publish, release:tweet

#1210 chore: Add Mailgun send email action
  .github/actions/send-email/README.md
  .github/actions/send-email/action.yml
  .github/actions/send-email/dist/index.js
  .github/actions/send-email/index.js
  .github/actions/send-email/package-lock.json
  .github/actions/send-email/package.json
  .github/workflows/nightly.yml
  test/integration/remote-config.spec.ts
Labels: release:stage
