Repository firebase/firebase-admin-node, pull requests merged in 2021-04, with the labels that each got.

#1212 chore: Clean up nightly workflow trigger tests
  test/integration/remote-config.spec.ts
Labels: release:stage

#1234 fix(rtdb): Fixing a token refresh livelock in Cloud Functions
  src/database/database-internal.ts
  src/firebase-app.ts
  test/unit/database/database.spec.ts
Labels: release-note

#1240 [chore] Release 9.7.0
  package.json
Labels: release:publish, release:tweet

#1235 chore: Merged main branch into modular-sdk
  .github/actions/send-email/README.md
  .github/actions/send-email/action.yml
  .github/actions/send-email/dist/index.js
  .github/actions/send-email/index.js
  .github/actions/send-email/package-lock.json
  .github/actions/send-email/package.json
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  CONTRIBUTING.md
  docgen/content-sources/node/HOME.md
  docgen/content-sources/node/toc.yaml
  docgen/generate-docs.js
  etc/firebase-admin.auth.api.md
  package-lock.json
  package.json
  src/app/firebase-app.ts
  src/auth/auth-api-request.ts
  src/auth/auth-config.ts
  src/auth/base-auth.ts
  src/auth/index.ts
  src/auth/tenant.ts
  src/auth/token-verifier.ts
  src/database/database.ts
  src/storage/storage.ts
  src/utils/error.ts
  src/utils/jwt.ts
  test/integration/auth.spec.ts
  test/integration/database.spec.ts
  test/integration/setup.ts
  test/unit/app/firebase-app.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth.spec.ts
  test/unit/auth/tenant-manager.spec.ts
  test/unit/auth/tenant.spec.ts
  test/unit/auth/token-verifier.spec.ts
  test/unit/database/database.spec.ts
  test/unit/index.spec.ts
  test/unit/messaging/messaging.spec.ts
  test/unit/storage/storage.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release:stage
