Repository firebase/firebase-admin-node, pull requests merged in 2021-02, with the labels that each got.

#1147 feat: Exporting all types of Messages so they can be used by consumers
  src/messaging/index.ts
  test/unit/messaging/messaging.spec.ts
Labels: release-note

#769 feat(auth): Implement getUserByProviderId
  etc/firebase-admin.api.md
  src/auth/auth-api-request.ts
  src/auth/auth.ts
  src/auth/index.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth.spec.ts
Labels: release-note

#770 feat(auth): Add ability to link a federated ID with the `updateUser()` method.
  etc/firebase-admin.api.md
  src/auth/auth-api-request.ts
  src/auth/auth.ts
  src/auth/index.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth.spec.ts
Labels: release-note

#1167 [chore] Release 9.5.0
  package.json
Labels: release:publish, release:tweet

#1173 fix: Updated integration tests to use the modular API surface
  test/integration/app.spec.ts
  test/integration/auth.spec.ts
  test/integration/database.spec.ts
  test/integration/firestore.spec.ts
  test/integration/instance-id.spec.ts
  test/integration/machine-learning.spec.ts
  test/integration/messaging.spec.ts
  test/integration/project-management.spec.ts
  test/integration/remote-config.spec.ts
  test/integration/security-rules.spec.ts
  test/integration/setup.ts
  test/integration/storage.spec.ts
Labels: release:stage
