Repository firebase/firebase-admin-node, pull requests merged in 2021-05, with the labels that each got.

#1246 fix(auth): adds missing EMAIL_NOT_FOUND error code
  src/utils/error.ts
Labels: release-note

#1245 Migrate FAC code
  .github/scripts/run_integration_tests.sh
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .gitignore
  docgen/content-sources/node/toc.yaml
  etc/firebase-admin.api.md
  package-lock.json
  package.json
  src/app-check/app-check-api-client-internal.ts
  src/app-check/app-check.ts
  src/app-check/index.ts
  src/app-check/token-generator.ts
  src/app-check/token-verifier.ts
  src/auth/auth.ts
  src/auth/token-generator.ts
  src/firebase-app.ts
  src/firebase-namespace-api.ts
  src/firebase-namespace.d.ts
  src/firebase-namespace.ts
  src/utils/crypto-signer.ts
  src/utils/jwt.ts
  test/integration/app-check.spec.ts
  test/resources/mock.jwks.json
  test/resources/mocks.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/app-check/app-check.spec.ts
  test/unit/app-check/token-generator.spec.ts
  test/unit/app-check/token-verifier.spec.ts
  test/unit/auth/token-generator.spec.ts
  test/unit/auth/token-verifier.spec.ts
  test/unit/firebase-app.spec.ts
  test/unit/firebase-namespace.spec.ts
  test/unit/firebase.spec.ts
  test/unit/index.spec.ts
  test/unit/utils/crypto-signer.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release:stage

#1250 feat(rtdb): Upgraded RTDB and other @firebase dependencies
  package-lock.json
  package.json
Labels: release-note

#1249 feat: Added ESM entry points to the package
  .github/scripts/verify_package.sh
  entrypoints.json
  generate-esm-wrapper.js
  generate-reports.js
  gulpfile.js
  package.json
  test/integration/postcheck/esm/example.test.js
  test/integration/postcheck/esm/package.json
  test/integration/postcheck/package.json
  test/integration/postcheck/tsconfig.json
  test/integration/postcheck/typescript/example-modular.test.ts
  test/integration/postcheck/typescript/example.test.ts
  test/integration/postcheck/typescript/example.ts
Labels: release:stage

#1264 feat: Add abuse reduction support
  .github/scripts/run_integration_tests.sh
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .gitignore
  docgen/content-sources/node/toc.yaml
  etc/firebase-admin.api.md
  package-lock.json
  package.json
  src/app-check/app-check-api-client-internal.ts
  src/app-check/app-check.ts
  src/app-check/index.ts
  src/app-check/token-generator.ts
  src/app-check/token-verifier.ts
  src/auth/auth.ts
  src/auth/token-generator.ts
  src/firebase-app.ts
  src/firebase-namespace-api.ts
  src/firebase-namespace.d.ts
  src/firebase-namespace.ts
  src/utils/crypto-signer.ts
  src/utils/jwt.ts
  test/integration/app-check.spec.ts
  test/resources/mock.jwks.json
  test/resources/mocks.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/app-check/app-check.spec.ts
  test/unit/app-check/token-generator.spec.ts
  test/unit/app-check/token-verifier.spec.ts
  test/unit/auth/token-generator.spec.ts
  test/unit/auth/token-verifier.spec.ts
  test/unit/firebase-app.spec.ts
  test/unit/firebase-namespace.spec.ts
  test/unit/firebase.spec.ts
  test/unit/index.spec.ts
  test/unit/utils/crypto-signer.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release-note, release:stage

#1266 [chore] Release 9.8.0
  package.json
Labels: release:publish, release:tweet

#1278 fix(auth): make MFA uid optional for updateUser operations
  src/auth/auth-api-request.ts
  test/unit/auth/auth-api-request.spec.ts
Labels: release-note

#1220 feat(auth): Added code flow support for OIDC flow.
  etc/firebase-admin.api.md
  src/auth/auth-config.ts
  src/auth/index.ts
  src/utils/error.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth-config.spec.ts
Labels: release-note

#1300 Update supported Node version to 10.13.0v and up
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: release-note

#1299 Fixed integration test failure of skipped tests
  test/integration/auth.spec.ts
Labels: release:stage

#1302 [chore] Release 9.9.0
  package.json
Labels: release:publish, release:tweet
