Repository firebase/firebase-admin-node, pull requests merged in 2022-11, with the labels that each got.

#1972 [chore] Release 11.2.1
  package.json
Labels: release:tweet, release:publish

#1960 feat(extensions): Add extensions namespace
  entrypoints.json
  etc/firebase-admin.extensions.api.md
  package.json
  src/extensions/extensions-api-client-internal.ts
  src/extensions/extensions-api.ts
  src/extensions/extensions.ts
  src/extensions/index.ts
  test/unit/extensions/extensions-api-client-internal.spec.ts
  test/unit/extensions/extensions.spec.ts
  test/unit/index.spec.ts
Labels: release-note

#1981 [chore] Release 11.3.0
  package.json
Labels: release:stage, release:tweet, release:publish
