Repository firebase/firebase-admin-node, pull requests merged in 2022-05, with the labels that each got.

#1676 Revert "feat(auth): Support sms region config change on Tenant and Project level."
  etc/firebase-admin.auth.api.md
  src/auth/auth-api-request.ts
  src/auth/auth-config.ts
  src/auth/auth.ts
  src/auth/index.ts
  src/auth/project-config-manager.ts
  src/auth/project-config.ts
  src/auth/tenant.ts
  test/integration/auth.spec.ts
  test/unit/auth/project-config-manager.spec.ts
  test/unit/auth/project-config.spec.ts
  test/unit/auth/tenant.spec.ts
Labels: release:stage

#1632 chore: Update App Check to V1 endpoints
  src/app-check/app-check-api-client-internal.ts
  src/app-check/token-generator.ts
  src/app-check/token-verifier.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/app-check/token-generator.spec.ts
Labels: release-note, release:stage

#1644 Implemented eventarc event publishing API (#1617)
  entrypoints.json
  etc/firebase-admin.eventarc.api.md
  package-lock.json
  package.json
  src/eventarc/cloudevent.ts
  src/eventarc/eventarc-client-internal.ts
  src/eventarc/eventarc-utils.ts
  src/eventarc/eventarc.ts
  src/eventarc/index.ts
  test/unit/eventarc/eventarc-utils.spec.ts
  test/unit/eventarc/eventarc.spec.ts
  test/unit/index.spec.ts
Labels: release:stage

#1688 [chore] Release 10.2.0
  package.json
Labels: release:tweet, release:publish
