Repository firebase/firebase-admin-node, pull requests merged in 2022-04, with the labels that each got.

#1635 Adding in alpha interface for blocking token verification
  etc/firebase-admin.api.md
  etc/firebase-admin.auth.api.md
  src/auth/auth-namespace.ts
  src/auth/base-auth.ts
  src/auth/index.ts
  src/auth/token-verifier.ts
  src/utils/error.ts
  test/resources/mocks.ts
  test/unit/auth/auth.spec.ts
  test/unit/auth/token-verifier.spec.ts
Labels: release:stage

#1654 [chore] Release 10.1.0
  package.json
Labels: release:tweet, release:publish

#1633 feat(auth): Support generate oob code request type VERIFY_AND_CHANGE_EMAIL
  etc/firebase-admin.auth.api.md
  src/auth/auth-api-request.ts
  src/auth/base-auth.ts
  src/utils/error.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth.spec.ts
Labels: release-note

#1673 feat(auth): Support sms region config change on Tenant and Project level.
  etc/firebase-admin.auth.api.md
  src/auth/auth-api-request.ts
  src/auth/auth-config.ts
  src/auth/auth.ts
  src/auth/index.ts
  src/auth/project-config-manager.ts
  src/auth/project-config.ts
  src/auth/tenant.ts
  test/integration/auth.spec.ts
  test/unit/auth/project-config-manager.spec.ts
  test/unit/auth/project-config.spec.ts
  test/unit/auth/tenant.spec.ts
Labels: release-note
