Repository firebase/firebase-admin-node, pull requests merged in 2023-05, with the labels that each got.

#2148 feat(appcheck): Added replay protection feature to App Check `verifyToken()` API
  etc/firebase-admin.api.md
  etc/firebase-admin.app-check.api.md
  src/app-check/app-check-api-client-internal.ts
  src/app-check/app-check-api.ts
  src/app-check/app-check-namespace.ts
  src/app-check/app-check.ts
  src/app-check/index.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/app-check/app-check.spec.ts
Labels: release-note

#2175 [chore] Release 11.8.0
  package.json
Labels: release:stage, release:tweet, release:publish

#2107 feat(auth): Add Password Policies support in Project and Tenant config
  etc/firebase-admin.auth.api.md
  src/auth/auth-config.ts
  src/auth/index.ts
  src/auth/project-config.ts
  src/auth/tenant.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-config.spec.ts
  test/unit/auth/project-config.spec.ts
  test/unit/auth/tenant.spec.ts
Labels: release-note, release:stage

#2183 fix Unsafe JavaScript Equality Checking
  src/auth/auth-api-request.ts
  src/auth/auth-config.ts
  src/auth/tenant.ts
  src/auth/token-verifier.ts
  src/remote-config/remote-config-api-client-internal.ts
Labels: release:stage

#2196 [chore] Release 11.9.0
  package.json
Labels: release:stage, release:tweet, release:publish
