Repository firebase/firebase-admin-node, pull requests merged in 2023-07, with the labels that each got.

#2216 feat(functions): Add features to task queue functions
  etc/firebase-admin.functions.api.md
  src/functions/functions-api-client-internal.ts
  src/functions/functions-api.ts
  src/functions/functions.ts
  src/functions/index.ts
  src/utils/validator.ts
  test/unit/functions/functions-api-client-internal.spec.ts
Labels: release-note

#2236 fix(auth): Memory Leak in AsyncHttpCall affecting auth.listUsers
  src/utils/api-request.ts
Labels: release-note, release:stage

#2246 [chore] Release 11.10.0
  package.json
Labels: release:stage, release:tweet, release:publish

#2247 fix: Revert "chore: upgrade database-compat"
  package-lock.json
  package.json
Labels: release-note

#2248 [chore] Release 11.10.1
  package.json
Labels: release:stage, release:tweet, release:publish
