Repository firebase/firebase-admin-node, pull requests merged in 2023-04, with the labels that each got.

#2140 chore: update app check integration tests
  test/integration/app-check.spec.ts
Labels: release:stage

#2139 [chore] Release 11.6.0
  package.json
Labels: release:stage, release:tweet, release:publish

#2147 chore: Upgrade dependencies in package.json
  package-lock.json
  package.json
Labels: release:stage

#2138 feat(fcm): Add `sendEach` and `sendEachForMulticast` for FCM batch send
  etc/firebase-admin.messaging.api.md
  src/messaging/messaging-api-request-internal.ts
  src/messaging/messaging.ts
  test/integration/messaging.spec.ts
  test/unit/messaging/messaging.spec.ts
Labels: release-note, release:stage

#2129 feat(auth): reCAPTCHA Public preview
  etc/firebase-admin.auth.api.md
  src/auth/auth-config.ts
  src/auth/index.ts
  src/auth/project-config-manager.ts
  src/auth/project-config.ts
  src/auth/tenant.ts
  src/utils/error.ts
  test/integration/auth.spec.ts
  test/unit/auth/project-config-manager.spec.ts
  test/unit/auth/project-config.spec.ts
  test/unit/auth/tenant.spec.ts
Labels: release-note, release:stage

#2158 [chore] Release 11.7.0
  package.json
Labels: release:tweet, release:publish
