Repository firebase/firebase-admin-node, pull requests merged in 2023-11, with the labels that each got.

#2385 chore(deps): bump google-cloud/firestore to 6.8.0
  package-lock.json
  package.json
Labels: release-note, release:stage

#2387 [chore] Release 11.11.1
  package.json
Labels: release:stage, release:tweet, release:publish

#2392 chore(deps): bump google-cloud/firestore and google-cloud/storage
  package-lock.json
  package.json
Labels: release:stage

#1974 change(ml): Drop the feature to publish from an AutoML Model
  etc/firebase-admin.api.md
  etc/firebase-admin.machine-learning.api.md
  src/machine-learning/index.ts
  src/machine-learning/machine-learning-api-client.ts
  src/machine-learning/machine-learning-namespace.ts
  src/machine-learning/machine-learning.ts
  test/integration/machine-learning.spec.ts
  test/unit/machine-learning/machine-learning-api-client.spec.ts
Labels: release-note, release:stage
