Repository firebase/firebase-admin-node, pull requests merged in 2024-11, with the labels that each got.

#2466 change: Migrate credentials to use google-auth-library
  package-lock.json
  package.json
  src/app/credential-internal.ts
  src/functions/functions-api-client-internal.ts
  src/utils/index.ts
  test/resources/mocks.ts
  test/unit/app/credential-internal.spec.ts
  test/unit/app/firebase-namespace.spec.ts
  test/unit/app/index.spec.ts
  test/unit/firebase.spec.ts
  test/unit/firestore/firestore.spec.ts
  test/unit/utils/index.spec.ts
Labels: release-note, release:stage

#2756 change: Update Node support to 18
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  README.md
  package-lock.json
  package.json
Labels: release-note, release:stage

#2757 chore: Upgrade dependencies
  etc/firebase-admin.api.md
  etc/firebase-admin.app-check.api.md
  etc/firebase-admin.app.api.md
  etc/firebase-admin.auth.api.md
  etc/firebase-admin.data-connect.api.md
  etc/firebase-admin.database.api.md
  etc/firebase-admin.eventarc.api.md
  etc/firebase-admin.extensions.api.md
  etc/firebase-admin.firestore.api.md
  etc/firebase-admin.functions.api.md
  etc/firebase-admin.installations.api.md
  etc/firebase-admin.instance-id.api.md
  etc/firebase-admin.machine-learning.api.md
  etc/firebase-admin.messaging.api.md
  etc/firebase-admin.project-management.api.md
  etc/firebase-admin.remote-config.api.md
  etc/firebase-admin.security-rules.api.md
  etc/firebase-admin.storage.api.md
  package-lock.json
  package.json
Labels: release-note, release:stage

#2759 change(fcm): Remove deprecated FCM APIs
  etc/firebase-admin.api.md
  etc/firebase-admin.messaging.api.md
  src/messaging/batch-request-internal.ts
  src/messaging/index.ts
  src/messaging/messaging-api-request-internal.ts
  src/messaging/messaging-api.ts
  src/messaging/messaging-namespace.ts
  src/messaging/messaging.ts
  test/unit/index.spec.ts
  test/unit/messaging/batch-requests.spec.ts
  test/unit/messaging/messaging.spec.ts
Labels: release-note, release:stage

#2763 chore: Add `X-Goog-Api-Client` metric header to outgoing authorized http requests
  src/auth/auth-api-request.ts
  src/messaging/messaging-api-request-internal.ts
  src/utils/api-request.ts
  src/utils/index.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/data-connect/data-connect-api-client-internal.spec.ts
  test/unit/database/database.spec.ts
  test/unit/eventarc/eventarc.spec.ts
  test/unit/extensions/extensions-api-client-internal.spec.ts
  test/unit/functions/functions-api-client-internal.spec.ts
  test/unit/installations/installations-request-handler.spec.ts
  test/unit/machine-learning/machine-learning-api-client.spec.ts
  test/unit/messaging/messaging.spec.ts
  test/unit/project-management/project-management-api-request.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/security-rules/security-rules-api-client.spec.ts
  test/unit/utils/crypto-signer.spec.ts
Labels: release:stage

#2760 change(rc): Update Remote Config condition evaluation hashing
  src/remote-config/condition-evaluator-internal.ts
  test/unit/remote-config/condition-evaluator.spec.ts
Labels: release-note, release:stage

#2761 fix: Set the Quota Project ID only for ADC human accounts
  src/app/credential-internal.ts
  src/utils/api-request.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/data-connect/data-connect-api-client-internal.spec.ts
  test/unit/extensions/extensions-api-client-internal.spec.ts
  test/unit/functions/functions-api-client-internal.spec.ts
  test/unit/machine-learning/machine-learning-api-client.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/security-rules/security-rules-api-client.spec.ts
  test/unit/utils/api-request.spec.ts
Labels: release-note, release:stage

#2764 [chore] Release 13.0.0
  package.json
Labels: release:stage, release:publish

#2779 fix: Fix the property names when initializing the SDK with the `ServiceAccount` type
  src/app/credential-internal.ts
Labels: release-note, release:stage

#2780 [chore] Release 13.0.1
  package.json
Labels: release:stage, release:publish
