Repository firebase/firebase-admin-node, pull requests merged in 2024-08, with the labels that each got.

#2648 fix: `getToken()` returns existing promise to a token if one exists instead of a new token.
  src/app/firebase-app.ts
  test/integration/messaging.spec.ts
  test/unit/app/firebase-app.spec.ts
Labels: release-note

#2666 chore: Skip sendToDeviceGroup integration test
  test/integration/messaging.spec.ts
Labels: release:stage

#2667 [chore] Release 12.3.1
  package.json
Labels: release:stage, release:publish

#2683 chore(fcm): Deprecate sendToTopic and Condition
  etc/firebase-admin.messaging.api.md
  src/messaging/messaging.ts
  test/integration/messaging.spec.ts
Labels: release-note, release:stage

#2674 [chore] Release 12.4.0
  package.json
Labels: release:stage, release:publish
