Repository firebase/firebase-admin-node, pull requests merged in 2024-09, with the labels that each got.

#2689 fix(app-check): support `httpAgent` in `JwksFetcher`
  src/app-check/token-verifier.ts
  src/utils/jwt.ts
  test/unit/app-check/token-verifier.spec.ts
  test/unit/utils/jwt.spec.ts
Labels: release-note

#2665 feat(rc): SSRC targeting
  etc/firebase-admin.remote-config.api.md
  src/remote-config/condition-evaluator-internal.ts
  src/remote-config/index.ts
  src/remote-config/remote-config-api.ts
  test/unit/remote-config/condition-evaluator.spec.ts
Labels: release-note, release:stage

#2702 [chore] Release 12.5.0
  package.json
Labels: release:stage, release:publish

#2703 [chore] Release 12.5.0 Take 2
  .github/workflows/release.yml
Labels: release:stage, release:publish

#2712 fix(auth): Add missing `Math.floor()` when setting `validDuration` in `createSessionCookie()`
  src/auth/auth-api-request.ts
  test/integration/auth.spec.ts
  test/unit/auth/auth-api-request.spec.ts
Labels: release-note, release:stage

#2701 feat: Add Data Connect API
  entrypoints.json
  etc/firebase-admin.data-connect.api.md
  package.json
  src/data-connect/data-connect-api-client-internal.ts
  src/data-connect/data-connect-api.ts
  src/data-connect/data-connect.ts
  src/data-connect/index.ts
  test/integration/data-connect.spec.ts
  test/unit/data-connect/data-connect-api-client-internal.spec.ts
  test/unit/data-connect/index.spec.ts
Labels: release-note, release:stage

#2715 [chore] Release 12.6.0
  package.json
Labels: release:stage, release:publish
