Repository firebase/firebase-admin-node, pull requests merged in 2024-10, with the labels that each got.

#2726 fix(functions): Allow both partial and full resource names to enqueue tasks in emulator
  src/functions/functions-api-client-internal.ts
Labels: release-note

#2625 feat(auth): Add recaptcha and sms toll fraud support for phone auth
  etc/firebase-admin.auth.api.md
  src/auth/auth-config.ts
  src/auth/index.ts
  src/auth/project-config.ts
  src/auth/tenant.ts
  test/integration/auth.spec.ts
  test/unit/auth/project-config.spec.ts
  test/unit/auth/tenant.spec.ts
Labels: release-note, release:stage

#2736 chore: fix data connect integration tests
  test/integration/data-connect.spec.ts
Labels: release:stage

#2737 chore: Update auth.spec.ts
  test/integration/auth.spec.ts
Labels: release:stage

#2738 chore: Add `X-Goog-Api-Client` metric header to Auth and FCM requests
  src/auth/auth-api-request.ts
  src/messaging/messaging-api-request-internal.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/messaging/messaging.spec.ts
Labels: release:stage

#2739 fix: Pin `@firebase/database-compat` to `v1.0.8`
  package-lock.json
  package.json
Labels: release-note, release:stage

#2741 [chore] Release 12.7.0
  package.json
Labels: release:stage, release:publish

#2745 feat(fcm): Add directBootOk field to AndroidConfig
  etc/firebase-admin.messaging.api.md
  src/messaging/messaging-api.ts
  src/messaging/messaging-internal.ts
  test/integration/messaging.spec.ts
  test/unit/messaging/messaging.spec.ts
Labels: release-note, release:stage

#2749 chore: Add integration tests for changes related to FDL deprecation
  test/integration/auth.spec.ts
Labels: release:stage
