Repository firebase/firebase-admin-node, pull requests merged in 2024-05, with the labels that each got.

#2151 fix: Export error classes
  src/app/index.ts
  src/auth/index.ts
  src/database/index.ts
  src/firestore/index.ts
  src/installations/index.ts
  src/instance-id/index.ts
  src/messaging/index.ts
  src/project-management/index.ts
Labels: release-note

#2549 Fix api extractor issues to expose error types
  etc/firebase-admin.app.api.md
  etc/firebase-admin.auth.api.md
  etc/firebase-admin.database.api.md
  etc/firebase-admin.firestore.api.md
  etc/firebase-admin.installations.api.md
  etc/firebase-admin.instance-id.api.md
  etc/firebase-admin.messaging.api.md
  etc/firebase-admin.project-management.api.md
  src/utils/error.ts
Labels: release:stage

#2561 [chore] Release 12.1.1
  package.json
Labels: release:stage, release:tweet, release:publish
