Repository firebase/firebase-admin-node, pull requests merged in 2024-06, with the labels that each got.

#2553 fix: Make ADC + human account work with firebase-admin
  src/utils/api-request.ts
  test/unit/app-check/app-check-api-client-internal.spec.ts
  test/unit/functions/functions-api-client-internal.spec.ts
  test/unit/machine-learning/machine-learning-api-client.spec.ts
  test/unit/remote-config/remote-config-api-client.spec.ts
  test/unit/security-rules/security-rules-api-client.spec.ts
Labels: release-note

#2603 fix: Replace `farmhash` with `farmhash-modern`
  package-lock.json
  package.json
  src/remote-config/condition-evaluator-internal.ts
  test/unit/remote-config/condition-evaluator.spec.ts
Labels: release-note, release:stage

#2605 [chore] Release 12.2.0
  package.json
Labels: release:stage, release:tweet, release:publish

#2615 chore: update integration test resources
  .github/resources/integ-service-account.json.gpg
Labels: release:stage
