Repository firebase/firebase-admin-node, pull requests merged in 2025-02, with the labels that each got.

#2840 chore: Update postcheck typescript version
  test/integration/postcheck/package.json
Labels: release:stage

#2752 feat(auth): Added FDL deprecation support for Firebase Auth
  etc/firebase-admin.auth.api.md
  src/auth/action-code-settings-builder.ts
  src/auth/auth-config.ts
  src/auth/base-auth.ts
  src/auth/index.ts
  src/auth/project-config.ts
  src/utils/error.ts
  test/integration/auth.spec.ts
  test/unit/auth/action-code-settings-builder.spec.ts
  test/unit/auth/auth-api-request.spec.ts
  test/unit/auth/auth-config.spec.ts
  test/unit/auth/auth.spec.ts
  test/unit/auth/project-config.spec.ts
Labels: release-note, release:stage

#2841 [chore] Release 13.1.0
  package.json
Labels: release:stage, release:publish

#2844 feat(fdc): Add support for Data Connect Impersonation
  etc/firebase-admin.data-connect.api.md
  src/data-connect/data-connect-api-client-internal.ts
  src/data-connect/data-connect-api.ts
  src/data-connect/index.ts
  test/integration/data-connect.spec.ts
Labels: release-note, release:stage
